//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public int id { get; set; }
        public int orderID { get; set; }
        public int itemID { get; set; }
        public int quantity { get; set; }
        public decimal price { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Order Order { get; set; }
    }
}
