//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderLines = new HashSet<OrderLine>();
        }
    
        public int orderID { get; set; }
        public int staffID { get; set; }
        public string customerID { get; set; }
        public System.DateTime orderStartDate { get; set; }
        public Nullable<System.DateTime> orderEndDate { get; set; }
        public int generatedReceipt { get; set; }
        public int isPaid { get; set; }
        public string pointsChoice { get; set; }
        public decimal Price { get; set; }
    
        public virtual ICollection<OrderLine> OrderLines { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
