//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace RestaurantSoftware.Models
{
    using System;
    using System.Collections.Generic;
    public partial class Customer
    {
        public int customerID { get; set; }
        public string customerEmail { get; set; }
        public string customerPass { get; set; }
        public string customerAddress { get; set; }
        public string customerPhone { get; set; }
        public int customerLoyaltyPoints { get; set; }
    }
}