//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.OrderLines = new HashSet<OrderLine>();
        }
    
        public int itemID { get; set; }
        public string itemName { get; set; }
        public int itemType { get; set; }
        public decimal itemPrice { get; set; }
    
        public virtual ItemType ItemType1 { get; set; }
        public virtual ICollection<OrderLine> OrderLines { get; set; }
    }
}
